name: KV Golf
favicon: null
layout_spectrum: 0.12512592738494277
typography_spectrum: 0.20592071558348835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7244099704548717
  lightness: 0.9120592589024454
  saturation: 0.430850604781881
  rhythmicContrast: 0.4253557715564966
purpose: []
